In [ ]:
Running the model in serial model using adaptive bisquare 

In [38]:
from sgwr import ALPHA, SGWR, fastsgwr
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np

data = pd.read_csv(r"\Crime.csv")

data = np.array(data)

x_x = data[0:, 0]  # x coordinate
y_y = data[0:, 1]  # y coordiante

g_x = data[0:, 3:]
g_y = data[0:, 2].reshape(-1, 1)

g_x = np.array(g_x, dtype=float)
g_y = np.array(g_y, dtype=float)

## If you decide to standardize your data. If you don't want to standardize it, just uncommand this part
scaler_x = StandardScaler()
scaler_y = StandardScaler()
g_x = scaler_x.fit_transform(g_x)
g_y = scaler_y.fit_transform(g_y)
#######

x_x = pd.Series(x_x)
y_y = pd.Series(y_y)

g_coords = np.column_stack((x_x, y_y))

data = data[0:, 3:]    
data = pd.DataFrame(data)

selector = ALPHA(g_coords, g_y, g_x, data)
bw, alpha = selector.fit()
print('Optimized alpha', alpha)
print('BW:', bw)

sgwr_model = SGWR(g_coords, g_y, g_x, bw, data, alpha)
result = sgwr_model.fit()

print('R2 ', result.R2)
print('Adjusted R2: ', result.adj_R2)
print('AICc ', result.aicc)

Bandwidth optimization using golden section based on AICc values...
BW: 1116.000 >>> AICc Score: 6461.938
BW: 1775.000 >>> AICc Score: 6623.366
BW: 709.000 >>> AICc Score: 6351.015
BW: 457.000 >>> AICc Score: 6253.635
BW: 302.000 >>> AICc Score: 6163.870
BW: 205.000 >>> AICc Score: 5812.680
BW: 146.000 >>> AICc Score: 5596.470
BW: 109.000 >>> AICc Score: 5551.445
BW: 87.000 >>> AICc Score: 5397.173
BW: 73.000 >>> AICc Score: 5440.707
BW: 95.000 >>> AICc Score: 5501.102
BW: 81.000 >>> AICc Score: 5407.271
BW: 90.000 >>> AICc Score: 5420.926
BW: 84.000 >>> AICc Score: 5405.600
BW: 88.000 >>> AICc Score: 5400.101
BW: 86.000 >>> AICc Score: 5402.001

Optimal BW: 87.000

Alpha optimization using bandwidth: 87.0

Alpha: 0.700 >>> AICc Score: 5263.083
Alpha: 0.500 >>> AICc Score: 5153.428
Alpha: 0.100 >>> AICc Score: 5220.677
Alpha: 0.400 >>> AICc Score: 5090.197
Alpha: 0.300 >>> AICc Score: 5023.729
Alpha: 0.200 >>> AICc Score: 4978.999

Best alpha value (divide and conquer): 0.2
Optimized a

In [ ]:
Running the model in serial model using fixed gaussian kernel

In [40]:
from sgwr import ALPHA, SGWR, fastsgwr
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np


data = pd.read_csv(r"\Crime.csv")

data = np.array(data)

x_x = data[0:, 0]  # x coordinate
y_y = data[0:, 1]  # y coordiante

g_x = data[0:, 3:]
g_y = data[0:, 2].reshape(-1, 1)

g_x = np.array(g_x, dtype=float)
g_y = np.array(g_y, dtype=float)

## If you decide to standardize your data. If you don't want to standardize it, just uncommand this part
scaler_x = StandardScaler()
scaler_y = StandardScaler()
g_x = scaler_x.fit_transform(g_x)
g_y = scaler_y.fit_transform(g_y)
#######

x_x = pd.Series(x_x)
y_y = pd.Series(y_y)

g_coords = np.column_stack((x_x, y_y))

data = data[0:, 3:]    
data = pd.DataFrame(data)

selector = ALPHA(g_coords, g_y, g_x, data, fixed=True, kernel='gaussian')
bw, alpha = selector.fit()
print('Optimized alpha', alpha)
print('BW:', bw)

sgwr_model = SGWR(g_coords, g_y, g_x, bw, data, alpha, fixed=True, kernel='gaussian')
result = sgwr_model.fit()

print('R2 ', result.R2)
print('Adjusted R2: ', result.adj_R2)
print('AICc ', result.aicc)

Bandwidth optimization using golden section based on AICc values...
BW: 43.258 >>> AICc Score: 7302.231
BW: 69.986 >>> AICc Score: 7336.605
BW: 26.739 >>> AICc Score: 7222.670
BW: 16.529 >>> AICc Score: 7072.016
BW: 10.220 >>> AICc Score: 6867.326
BW: 6.320 >>> AICc Score: 6554.055
BW: 3.910 >>> AICc Score: 6350.290
BW: 2.420 >>> AICc Score: 6176.006
BW: 1.500 >>> AICc Score: 5977.212
BW: 0.931 >>> AICc Score: 5583.038
BW: 0.579 >>> AICc Score: 5812.896
BW: 1.148 >>> AICc Score: 5839.988
BW: 0.796 >>> AICc Score: 5513.583
BW: 0.713 >>> AICc Score: 5562.526
BW: 0.848 >>> AICc Score: 5517.769
BW: 0.765 >>> AICc Score: 5523.877
BW: 0.816 >>> AICc Score: 5511.952
BW: 0.828 >>> AICc Score: 5512.897
BW: 0.808 >>> AICc Score: 5512.128
BW: 0.821 >>> AICc Score: 5512.169
BW: 0.813 >>> AICc Score: 5511.943
BW: 0.811 >>> AICc Score: 5511.987
BW: 0.814 >>> AICc Score: 5511.936
BW: 0.815 >>> AICc Score: 5511.939
BW: 0.814 >>> AICc Score: 5511.936

Optimal BW: 0.814

Alpha optimization using bandwid

In [41]:
## Once the model is fit, you can extract the coef for your data using the below command. 
result.params

array([[-1.39774765e-01, -2.81889632e+00,  1.50777886e+00,
        -2.37818696e-01,  1.22735389e-01, -2.07965361e-01],
       [ 1.28040487e+00,  9.66352239e+00,  3.82996578e+00,
        -1.87443754e+00,  1.18229530e+00, -9.84457369e-01],
       [-2.88583752e-03, -3.05582176e+00,  2.02391065e+00,
        -4.89615929e-01, -2.68660147e-02,  2.07972543e-01],
       ...,
       [ 7.71672698e-02, -3.67065508e+00,  1.61570837e+00,
         1.06981989e+00,  3.34928398e-01, -3.57726092e-01],
       [-7.12521247e-02, -1.45671994e+00,  1.12498975e+00,
        -1.76630199e-01,  5.71042288e-01,  4.78520092e-02],
       [ 1.32038777e-01, -1.77497016e+00,  7.99119276e-01,
         1.44264943e+00, -5.63207198e-02, -2.46938243e-02]])

In [43]:
## summary table of the model 
print(result.summary())

Model type                                                         Gaussian
Number of observations:                                                2841
Number of covariates:                                                     6

Global Regression Results
---------------------------------------------------------------------------
Residual sum of squares:                                           2207.531
Log-likelihood:                                                   -3672.838
AIC:                                                               7357.677
AICc:                                                              7359.717
BIC:                                                             -20336.138
R2:                                                                   0.223
Adj. R2:                                                              0.222

Variable                              Est.         SE  t(Est/SE)    p-value
------------------------------- ---------- ---------- ------

In [44]:
## printing local R-squared 
lcl_r2 = result.localR2
lcl_r2

array([[0.9352124 ],
       [0.92537379],
       [0.9199739 ],
       ...,
       [0.90930632],
       [0.9920958 ],
       [0.990704  ]])

In [45]:
## constracting hypothesis test 
filter_tvalue = result.filter_tvals()
filter_tvalue

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [6.26913519, 4.04477082, 3.79964624, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [46]:
# filter t values with 95% confidence interval
filter_95 = result.filter_tvals(alpha=0.05) 
filter_95

array([[ 0.        ,  0.        ,  2.48168059,  0.        ,  0.        ,
         0.        ],
       [ 6.26913519,  4.04477082,  3.79964624, -3.12701071,  0.        ,
        -2.52198576],
       [ 0.        ,  0.        ,  2.82962071,  0.        ,  0.        ,
         0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])