In [ ]:
Running the model in serial model using adaptive bisquare 

In [5]:
from sgwr import ALPHA, SGWR, fastsgwr
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np
import time


sart_t = datetime.datetime.now()
data = pd.read_csv(r"\Crime.csv")
columns = data.columns[3:]

data = np.array(data)

x_x = data[0:, 0]  # x coordinate
y_y = data[0:, 1]  # y coordiante

g_x = data[0:, 3:]
g_y = data[0:, 2].reshape(-1, 1)

g_x = np.array(g_x, dtype=float)
g_y = np.array(g_y, dtype=float)

## If you decide to standardize your data. If you don't want to standardize it, just uncommand this part
scaler_x = StandardScaler()
scaler_y = StandardScaler()
g_x = scaler_x.fit_transform(g_x)
g_y = scaler_y.fit_transform(g_y)
#######

x_x = pd.Series(x_x)
y_y = pd.Series(y_y)

g_coords = np.column_stack((x_x, y_y))

data = data[0:, 3:]    
data = pd.DataFrame(data)

selector = ALPHA(g_coords, g_y, g_x, data)
bw, alpha = selector.fit()
print('Optimized alpha', alpha)
print('BW:', bw)

sgwr_model = SGWR(g_coords, g_y, g_x, bw, data, alpha)
result = sgwr_model.fit()

print('R2 ', result.R2)
print('Adjusted R2: ', result.adj_R2)
print('AICc ', result.aicc)

Bandwidth optimization using golden section based on AICc values...
BW: 43.258 >>> AICc Score: 7302.231
BW: 69.986 >>> AICc Score: 7336.605
BW: 26.739 >>> AICc Score: 7222.670
BW: 16.529 >>> AICc Score: 7072.016
BW: 10.220 >>> AICc Score: 6867.326
BW: 6.320 >>> AICc Score: 6554.055
BW: 3.910 >>> AICc Score: 6350.290
BW: 2.420 >>> AICc Score: 6176.006
BW: 1.500 >>> AICc Score: 5977.212
BW: 0.931 >>> AICc Score: 5583.038
BW: 0.579 >>> AICc Score: 5812.896
BW: 1.148 >>> AICc Score: 5839.988
BW: 0.796 >>> AICc Score: 5513.583
BW: 0.713 >>> AICc Score: 5562.526
BW: 0.848 >>> AICc Score: 5517.769
BW: 0.765 >>> AICc Score: 5523.877
BW: 0.816 >>> AICc Score: 5511.952
BW: 0.828 >>> AICc Score: 5512.897
BW: 0.808 >>> AICc Score: 5512.128
BW: 0.821 >>> AICc Score: 5512.169
BW: 0.813 >>> AICc Score: 5511.943
BW: 0.811 >>> AICc Score: 5511.987
BW: 0.814 >>> AICc Score: 5511.936
BW: 0.815 >>> AICc Score: 5511.939
BW: 0.814 >>> AICc Score: 5511.936

Optimal BW: 0.814

Alpha optimization using bandwid

In [ ]:
Running the model in serial model using fixed gaussian kernel

In [ ]:
from sgwr import ALPHA, SGWR, fastsgwr
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np
import time


sart_t = datetime.datetime.now()
data = pd.read_csv(r"\Crime.csv")
columns = data.columns[3:]

data = np.array(data)

x_x = data[0:, 0]  # x coordinate
y_y = data[0:, 1]  # y coordiante

g_x = data[0:, 3:]
g_y = data[0:, 2].reshape(-1, 1)

g_x = np.array(g_x, dtype=float)
g_y = np.array(g_y, dtype=float)

## If you decide to standardize your data. If you don't want to standardize it, just uncommand this part
scaler_x = StandardScaler()
scaler_y = StandardScaler()
g_x = scaler_x.fit_transform(g_x)
g_y = scaler_y.fit_transform(g_y)
#######

x_x = pd.Series(x_x)
y_y = pd.Series(y_y)

g_coords = np.column_stack((x_x, y_y))

data = data[0:, 3:]    
data = pd.DataFrame(data)

selector = ALPHA(g_coords, g_y, g_x, data, fixed=True, kernel='gaussian')
bw, alpha = selector.fit()
print('Optimized alpha', alpha)
print('BW:', bw)

sgwr_model = SGWR(g_coords, g_y, g_x, bw, data, alpha, fixed=True, kernel='gaussian')
result = sgwr_model.fit()

print('R2 ', result.R2)
print('Adjusted R2: ', result.adj_R2)
print('AICc ', result.aicc)

In [6]:
## Once the model is fit, you can extract the coef for your data using the below command. 
result.params

array([[-1.39774765e-01, -2.81889632e+00,  1.50777886e+00,
        -2.37818696e-01,  1.22735389e-01, -2.07965361e-01],
       [ 1.28040487e+00,  9.66352239e+00,  3.82996578e+00,
        -1.87443754e+00,  1.18229530e+00, -9.84457369e-01],
       [-2.88583752e-03, -3.05582176e+00,  2.02391065e+00,
        -4.89615929e-01, -2.68660147e-02,  2.07972543e-01],
       ...,
       [ 7.71672698e-02, -3.67065508e+00,  1.61570837e+00,
         1.06981989e+00,  3.34928398e-01, -3.57726092e-01],
       [-7.12521247e-02, -1.45671994e+00,  1.12498975e+00,
        -1.76630199e-01,  5.71042288e-01,  4.78520092e-02],
       [ 1.32038777e-01, -1.77497016e+00,  7.99119276e-01,
         1.44264943e+00, -5.63207198e-02, -2.46938243e-02]])

In [98]:
## summary table of the model 
result.summary()

Model type                                                         Gaussian
Number of observations:                                                2841
Number of covariates:                                                     6

Global Regression Results
---------------------------------------------------------------------------
Residual sum of squares:                                           2207.531
Log-likelihood:                                                   -3672.838
AIC:                                                               7357.677
AICc:                                                              7359.717
BIC:                                                             -20336.138
R2:                                                                   0.223
Adj. R2:                                                              0.222

Variable                              Est.         SE  t(Est/SE)    p-value
------------------------------- ---------- ---------- ------

In [100]:
## printing local R-squared 
lcl_r2 = result.localR2
lcl_r2

[[0.93380447]
 [0.92368197]
 [0.91803074]
 ...
 [0.90635788]
 [0.99187591]
 [0.9906056 ]]


In [101]:
## constracting hypothesis test 
filter_tvalue = result.filter_tvals()
filter_tvalue

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [6.21938574, 4.0116945 , 3.76752806, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [102]:
# filter t values with 95% confidence interval
filter_95 = result.filter_tvals(alpha=0.05) 
filter_95

array([[ 0.        ,  0.        ,  2.4614197 ,  0.        ,  0.        ,
         0.        ],
       [ 6.21938574,  4.0116945 ,  3.76752806, -3.09646716,  0.        ,
        -2.49496668],
       [ 0.        ,  0.        ,  2.80665245,  0.        ,  0.        ,
         0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])